sudo: required

language: generic

services:
    - docker

before_install:
    - docker build -t jgiammona/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jgiammona/docker-react npm run test